mediums:
  - medium:
      name: Meduza
      medium-url: https://meduza.io/
      html-preview-tags:
        article: article
        tag: .RichBlock-tag
        title: .BlockTitle-first
        subtitle: .BlockTitle-second
        article-url: .Link-root
      html-article-tags:
        author: .MaterialNote-module_note_caption__1ezSo
        date: .Timestamp-module_root__coOvT
        text: .GeneralMaterial-article
  - medium:
      name: Kp
      medium-url: https://www.kp.ru/online/
      html-preview-tags:
        article: .styled__DigestItemWrapper-sc-1tputnk-13
        tag: .styled__TagDesktop-sc-1tputnk-11
        title: .styled__TitleLink-sc-1tputnk-2
        subtitle: .styled__DescriptionLink-sc-1tputnk-3
        article-url: .styled__TitleLink-sc-1tputnk-2
      html-article-tags:
        author: .styled__FullName-sc-1jl27nw-1
        date: .styled__Time-sc-j7em19-1
        text: .styled__Content-sc-1wayp1z-0

persistence:
  filename: mediums
  interval: 120

