
version: "3.7"
services:
  nlp:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-nlp-server
    ports:
      - "7070:7070"
    volumes:
      - $PWD/database:/database
      - $PWD/config:/config

