
FROM python:3.9

LABEL maintainer = "Pavel Erokgin <pavel.v.erokhin@gmail.com>"

WORKDIR /app

COPY ../nlp/requirements.txt .

RUN pip install -r requirements.txt

COPY ../nlp .

CMD ["python", "./nlp_manager.py"]
