
FROM python:3.9

LABEL maintainer = "Pavel Erokhin <pavel.v.erokhin@gmail.com>"

RUN mkdir /database
RUN mkdir /config

WORKDIR /app

COPY ../nlp .

RUN pip install -r requirements.txt
RUN python -m spacy download ru_core_news_sm

CMD ["python", "app.py"]
