FROM golang:latest

LABEL maintainer = "Pavel Erokhin <pavel.v.erokhin@gmail.com>"
## Add the wait script to the image

# wait container with NLP going up first
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

RUN mkdir database

RUN mkdir config

WORKDIR /app
COPY ../scrapper .

RUN go mod download

RUN go build -o scrapper

CMD /wait

CMD ["./scrapper"]
